import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import LoginForm from '../../components/Login/LoginForm.tsx'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Blank App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="p-5 border-b-[1px] fixed w-full bg-white">
      <div>
            <a
              href="http://localhost:3000"
              rel="noopener noreferrer"
            >
              <Image
                src="/logo.svg"
                alt="Blank Logo"
                width={87}
                height={20}
                priority
              />
            </a>
          </div>
      </header>
      <main className="flex h-screen">
       <section className="flex flex-col p-20 justify-center w-1/3">
        <LoginForm />
       </section>
       {/* <section className="bg-blue-300 bg-gradient-to-r from-white w-full"> */}
       <section className="bg-gradient-to-l from-cyan-500 to-blue-500 w-full">
        <div className="flex h-screen justify-center items-center shadow-2xl">
        <Image 
          src="/login-screen.webp"
          alt="login image"
          width={488}
          height={488}
          priority
        />
        </div>
       </section>
      </main>
    </>
  )
}
